== Machine Learning

- Pattern Recognition And Machine Learning(PRML)
- Probabilistic Graphical Models(PGM)
- Bayesian Reasoning and Machine Learning(BRML)



== Linear Algebra

- [Introduction to Linear Algebra](http://genes.mit.edu/burgelab/yarden/strang_linear_algebra.pdf)
- [Linear Algebra and Its' Applications](http://math.bnu.edu.cn/~lijiequan/publications/Strang_Linear.Algebra.and.Its.Applications.4ed.pdf)

== Algorithm

- Algorithm design



== 编译器

　编译器领域相关有三本公认的经典书籍，龙书《Compilers: Principles, Techniques, and Tools 》，虎书《Modern Compiler Implementation in X (X表示各种语言)》，鲸书《Advanced Compiler Design and Implementation》
。其中龙书是编译理论方面公认的不二之选，而后面两本则对实践更有指导意义。另外@装配脑袋有个很好的编译器入门系列博客：http://www.cnblogs.com/Ninputer/archive/2011/06/07/2074632.html

== 熊猫书院
https://www.douban.com/doulist/44371165/?start=0&sort=time&sub_type=
自我管理
沟通协作
心理学
逻辑思维
科学素养
哲学素养
社会素养 
艺术素养
商业素养
拖延心理学
一万小时天才理论
自控力
如何阅读一本书
沟通的艺术（插图修订第14版）
非暴力沟通
学会提问
金字塔原理

社会性动物
对伪心理学说不
影响力
真实的幸福
思考的艺术
别做正常的傻瓜
决策与判断
系统之美
万物简史
自私的基因
魔鬼出没的世界
科学究竟是什么
哲学是什么
大问题
伦理学与生活
公正
理解公共政策
宽容
一课经济学
听音乐（插图第6版）
艺术
认识电影
素描的诀窍
商业模式新生代
精益创业
卓有成效的管理者

== todo

海都物语

== OOAD

Object-Oriented Software Construction, 2nd Edition 
Object-Oriented Analysis and Design With Applications, 2nd Edition 
Object-Oriented Software Engineering: A Use Case Driven Approach 
Design Patterns: Elements of Reusable Object-Oriented Software
Head First Object-Oriented Analysis and Design


= TO DO


= 读过的书

The Blue Book of Grammar and Punctuation(2016.9)

